name: awra2022
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10

  # HyRiver packages
  - async_retriever>=0.3.2
  - pygeoogc>=0.13
  - pygeoutils>=0.13
  - py3dep>=0.13
  - pynhd>=0.13
  - pygeohydro>=0.13
  - pydaymet>=0.13

  # Optional deps to speed up xarray and daymet
  - bottleneck
  - numba

  # Other third-party deps
  - cartopy
  - contextily
  - datashader
  - ipykernel
  - ipywidgets
  - mapclassify
  - proplot
  - pytables
  - xarray-spatial

  - pip
  - pip:
    - git+https://github.com/cheginit/async_retriever.git
    - git+https://github.com/cheginit/pygeoogc.git
    - git+https://github.com/cheginit/pygeoutils.git
    - git+https://github.com/cheginit/pynhd.git
    - git+https://github.com/cheginit/py3dep.git
    - git+https://github.com/cheginit/pydaymet.git
    - git+https://github.com/cheginit/pygeohydro.git
