name: awra2022
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10

  # HyRiver packages
  - async_retriever>=0.3.2
  - pygeoogc>=0.13
  - pygeoutils>=0.13
  - py3dep>=0.13
  - pynhd>=0.13
  - pygeohydro>=0.13
  - pydaymet>=0.13

  # Optional deps to speed up xarray and daymet
  - bottleneck
  - numba

  # Other third-party deps
  - cartopy
  - datashader
  - mapclassify
  - contextily
  - osmnx
  - pytables
  - ipykernel
  - ipywidgets
  - proplot
  - xarray-spatial
